version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - s-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@rjun#123"
      POSTGRES_DB: springdocker
    ports:
      - "5433:5432"
    networks:
      - s-network

networks:
    s-network:
      driver: bridge
